name: Django CI (Docker)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Create .env file
      run: |
       
        echo "APIKEY=${{ secrets.APIKEY }}" > .env
        echo "GROQ=${{ secrets.GROQ }}" >> .env
        echo "GROQQ=${{ secrets.GROQQ }}" >> .env
        echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" >> .env

        echo "DJANGO=${{ secrets.DJANGO }}" >> .env
     
    - name: Build Docker image
      run: |
        docker build -t django-app .
 
    - name: Run Django tests
      run: |
        docker run --env-file .env django-app python manage.py test
